echo "date|offender|statement" > deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/vargakevinlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/janeckaallenlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/ogancraiglast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/basscharleslast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/vasquezpablolast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/dinkinsrichardlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/mastersonrichardlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/esquivelrudylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/marquezmariolast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/drewrobertlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/stromanmarklast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/mcginnrickylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/barnesodelllast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/wilsonmarvinlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/hernandezramontorreslast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/woollsrandylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/lealhumbertolast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/pasterjameslast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/williamsrichardlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/cantupeterlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/taylorleelast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/brucekennethlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/bridgewarrenlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/martinezjohnnylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/lagroneedwardlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/hernandezjesselast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/porterjameslast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/hankinsterrylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/wattskevinlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/williamswalterlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/bigbyjameslast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/escamillalicholast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/goffdavidlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/jacksonderricklast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/garzarobertlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/rossvaughnlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/williamsjeffreylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/kerrcarylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/montoyairineolast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/parrcarrolllast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/doughtiejefferylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/feldersammielast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/hinesbobbylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/hermandavidlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/kinnamonraymondlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/paredesmiguellast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/parrkennethlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/barneswillislast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/kingcalvinlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/millergarrylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/grahamgarylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/woodsstevenlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/hernandezrodolfolast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/cruzjavierlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/butlerjeromelast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/williamsanthonylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/ramirezluislast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/mcwilliamsfredericklast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/wilkersonrichardlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/morrowrobertlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/rectorcharleslast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/pruettrobertlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/kincykevinlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/shannonwillielast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/lautiaualast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/sanmigueljessylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/teaguedelbertlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/evansmichaellast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/munizpedrolast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/bowerlesterlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/barberdannylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/woodsbobbylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/chamberstonylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/smithclydelast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/johnsonlonnielast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/lookingbillrobertlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/claykeithlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/stokerdavidlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/pylesjohnnylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/cockrumjohnlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/boggesscliffordlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/barnardharoldlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/nealycharleslast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/gallowaybillylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/caldwelljefferylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/clarkhermanlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/gibbsdavidlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/perrymichaellast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/livingstoncharleslast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/brimagerichardlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/cordovageorgelast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/aguilarjesuslast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/ortizricardolast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/chesterelroylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/fulleraaronlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/charlesderricklast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/johnsondorsielast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/tuckerjefferylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/amadorjohnlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/mooremichaellast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/mannfletcherlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/brewerlawrencelast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/carterrobertearllast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/blackrobertlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/trottiewillielast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/delunacarloslast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/robersonbrianlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/andersonnewtonlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/cobbrichardlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/johnsongarylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/coulsonrobertlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/moorejonathanlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/broussardwindelllast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/wolfebryanlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/greenedwardlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/jonesrichardlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/ellisedwardlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/turnerjessellast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/kunkletroylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/harriskennethlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/hittledaniellast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/whitemelvinlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/pattersontorontolast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/wyattwilliamlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/cuevasignaciolast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/vuonghailast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/gentrykennethlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/bradfordgaylandlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/rosalesmichaellast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/mannsdenardlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/morrowrickylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/dunnhenrylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/greendominiquelast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/burnswilliamlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/reevesreginaldlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/lawtonstaceylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/fuentesanthonylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/vegamartinlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/prietoarnoldlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/wilkinschristopherlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/birdjerrylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/brockkennethlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/hughesprestonlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/reyesgilbertolast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/romerojesuslast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/medinajavierlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/lambjohnlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/elizaldejaimelast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/matchettfarleylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/heiselbetzearllast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/bakerstanleylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/foustaaronlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/cottonmarcuslast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/zimmermankevinlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/albajohnlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/cantudomingolast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/yowellmichaellast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/hayeslarrylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/crankdentonlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/shamburgerronlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/rileymichaellast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/kellyalvinlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/maxwelljoshualast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/crawfordhiltonlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/threadgillronnielast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/harrisrobertlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/walkertonylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/richardmichaellast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/wilkensjameslast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/thurmondkeithlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/aldrichdonaldlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/lackeyclarencelast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/wheatjohnlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/gribbletimothylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/delkmontylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/dowthittdennislast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/sterlinggarylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/mitchellgeraldlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/moorecurtislast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/corwindaniellast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/claytonjameslast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/fullerjustinlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/mcfarlandfranklast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/cookbobbylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/powelljameslast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/mccullumdemarcolast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/no_last_statement.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/connerjohnnylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/fosterclevelast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/hearnyokamonlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/vasquezmanuellast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/chappellwilliamlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/russellcliftonlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/cartwrightrichardlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/russeaugregorylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/berkleywilliamlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/harrisdannylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/porterhenrylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/johnsonderricklast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/hafdahlrandalllast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/granadoscarloslast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/rodriguezlionelllast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/garciagustavolast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/motleyjefferylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/swainmariolast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/edwardsterrylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/vickersbillylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/lopezdaniellast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/kutznerrichardlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/morriskennethlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/williamsjeffrey999350last.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/joinerorienlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/sprousekentlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/gonzalesjoelast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/duffsmithmarkumlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/nevillerobertlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/doyleanthonylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/lockhartmichaellast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/jasperraylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/thomasshannonlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/roachtonylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/colemanchristopherlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/simpsondaniellelast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/pursleylonnielast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/jonestjlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/martinezjameslast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/wrightgregorylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/buxtonlawrencelast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/westleyanthonylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/andersonjohnnylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/bassosuzannelast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/farristroylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/robertsdonnielast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/davisjameslast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/hillmacklast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/greengwlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/jonesclaudelast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/hughestommielast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/johnsoneddielast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/roblesmartinlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/cardenasrubenlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/chavezjohnlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/reeselamontlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/pippinroylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/jacksondonelllast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/greenrickylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/davislarrylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/nicholsjosephlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/clarkjacklast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/medellinjoselast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/newburydonaldlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/hinojosarichardlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/garzamanuellast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/stonebenjaminlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/etheridgegarylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/wilsonjackielast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/soriajuanlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/moodystephenlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/moselydaroycelast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/mcduffkennethlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/maddenrobertlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/minielpeterlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/skillerndoylelast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/gutierrezvincentlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/barefieldjohnlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/williamswillielast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/martinezdavidlast999288.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/smithlarrylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/riddlegranvillelast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/miltoncharleslast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/camachogenarolast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/beazleynapoleonlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/turnercarltonlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/maysrexlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/adamsbeunkalast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/johnsoncarllast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/busbyjasenlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/floresmiguellast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/holidayraphaellast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/callinsbrucelast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/masseyjasonlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/cooksvincentlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/laddrobertlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/richardsonmiguellast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/whitelarrylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/whitakergeorgelast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/hernandezrodrigolast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/collierjameslast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/pondexterwillielast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/hernandezadophlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/carterrobertanthonylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/sellstommylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/tuttlecharleslast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/fullerbarneylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/lewisrickylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/johnsonkialast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/phillipscliffordlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/pinkertonjaylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/adanandusdwightlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/barefootthomaslast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/mathismiltonlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/freemanjamesllast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/frazierderricklast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/beathardjameslast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/morinstephenlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/hicksdavidlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/mccoskeyjamielast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/meanesjameslast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/daviswilliamlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/perezrobertlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/obrienderricklast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/blantonreginaldlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/dillinghamjefferylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/wesbrookcoylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/russelljameslast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/floresandrewlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/howardronaldlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/fearancejohnlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/ruizrolandolast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/cruzoliverlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/noblesjonathanlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/cookanthonylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/rogerspatricklast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/goodwinalvinlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/dicksonryanlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/burksjohnlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/resendizangellast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/brownmauriceolast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/garciafrankmlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/johnsonjohnnylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/fullertyronelast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/harrisdavidlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/wardadamlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/colemanlisalast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/allridgejameslast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/clarkdavidlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/castillodavidlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/morelandjameslast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/richardsonjameslast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/salazarrobertlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/hoppergeorgelast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/ransomkennethlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/oliverkhristianlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/behringerearllast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/bluecarllast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/chamberlainkarllast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/curryalvalast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/hughesbillylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/atworthrobertlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/moodyjohnlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/feldmandouglaslast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/nunciopaullast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/moorefranklast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/westrobertlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/masonthomaslast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/ruddemersonlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/robertsdouglaslast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/longdavidlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/scheanettedalelast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/martinezvirgillast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/kitchenswilliamlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/santellanjoselast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/rivasgeorgelast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/mayjustinlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/arnoldjermarrlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/emeryjefflast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/garciajuanlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/greenjonathanlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/tamayoedgarlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/mcbridemichaellast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/brookscharlielast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/mccarthykimberlylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/herronjermainelast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/willinghamcameronlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/ransomcedriclast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/andersonrobertlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/jacobsbrucelast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/preyortaichinlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/dorseyleonlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/villegasjoselast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/thackercharleslast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/titsworthtimothylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/belyeucliftonlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/wootenlarrylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/salazarluislast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/goodmanspencerlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/hallmichaellast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/sattiewhitevernonlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/gardnerbillylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/derrickmikellast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/knightpatricklast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/jacksontommylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/sharpmichaellast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/sigalamichaellast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/gosscorneliuslast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/hererraleonellast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/tuckerkarlalast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/losadadavislast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/styronronfordlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/valleyosvanislast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/obryanronaldlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/murraywilliamlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/perkinsreginaldlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/webbfreddielast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/rumbaughcharleslast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/kellycarllast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/jacobsjesselast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/murphyivanlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/diazarturolast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/hudsonrobertlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/hernandezramirolast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/duncanrichardlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/pattersonkelseylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/gutierrezjoselast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/hoguejerrylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/gutierrezjessielast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/alixfranklinlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/jacksonjameslast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/spencedavidlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/rodriguezmichaellast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/gallamoresamuellast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/esparzaguadalupelast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/jonesgeorgelast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/quintanillajohnlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/thompsonrobertlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/martinjerrylast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/rowellrobertlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/taylorelkielast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/renfrostevenlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/fosterrichardlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/boydcharleslast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/tignergeraldlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/cranealvinlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/martinezalexanderlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/kingleonlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/colburnjameslast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/netherystephenlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/bagwelldennislast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/martinezdavidlast999173.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/riesjosephlast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/clarkjameslast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/chihelibertolast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/cannadyrogeliolast.html >> html >> deathrow.csv
node scraper.js https://www.tdcj.state.tx.us/death_row/dr_info/cannonjosephlast.html >> html >> deathrow.csv
